Better input prompts

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -9,35 +9,52 @@ fi
 
 # Install paru if it doesn't exist
 if ! command -v paru &>/dev/null; then
-    read -r -p "paru will be installed next, continue? [y/N]" continue
-    case "${continue}" in
-    y/Y) ;;
-    n/N) exit ;;
+    read -r -p "Install paru? [y/N]\n" if_install
+    if_install="${if_install:-n}"
+    case "${if_install}" in
+    y | Y)
+        sudo pacman -S --needed base-devel
+        cd /tmp || exit
+        git clone https://aur.archlinux.org/paru.git
+        cd paru || exit
+        makepkg -si
+        ;;
+    n | N) ;;
+    *)
+        echo "Invalid parameter"
+        exit
+        ;;
     esac
-    sudo pacman -S --needed base-devel
-    cd /tmp || exit
-    git clone https://aur.archlinux.org/paru.git
-    cd paru || exit
-    makepkg -si
 fi
 
 # Install programs that are required for all branches
-paru -Syu --needed zoxide fzf powerlevel10k zsh zsh-completions zsh-history-substring-search zsh-syntax-highlighting zsh-theme-powerlevel10k-git zsh-autosuggestions git fd ripgrep trash-cli neovim duf dust pkgfile
+read -r -p "Install essential packages? [Y/n]\n" skip
+skip="${skip:-y}"
+case "${skip}" in
+y | Y)
+    paru -Syu --needed zoxide fzf powerlevel10k zsh zsh-completions zsh-history-substring-search zsh-syntax-highlighting zsh-theme-powerlevel10k-git zsh-autosuggestions git fd ripgrep trash-cli neovim duf dust pkgfile
+    ;;
+n | N) ;;
+*)
+    echo "Invalid parameter"
+    exit
+    ;;
+esac
+
+# Go back to work tree
+cd "${HOME}" || exit
 
 # An alias
 function cf {
     yadm "$@"
 }
 
-# Go back to work tree
-cd "${HOME}" || exit
-
 # Hide untracked files
 cf config status.showUntrackedFiles no
 
 # Switch to the desired branch
 cf branch -a
-read -r -p "Which branch do you want to use?" branch
+read -r -p "Which branch do you want to use?\n" branch
 cf checkout "${branch}"
 
 # Set origin, 'git clone' has done it
@@ -54,7 +71,16 @@ cf branch --set-upstream-to=origin/"${branch}" "${branch}"
 case "${branch}" in
 main)
     # Install different programs for different branches
-    sudo pacman -S ranger
+    read -r -p "Install ranger? [Y/n]\n" if_install
+    if_install="${if_install:-y}"
+    case "${if_install}" in
+    y | Y) sudo pacman -S ranger ;;
+    n | N) ;;
+    *)
+        echo "Invalid parameter"
+        exit
+        ;;
+    esac
     ;;
 light) ;;
 *)
@@ -65,7 +91,8 @@ esac
 
 # Force a checkout
 cf status
-read -r -p "Do you want to force the checkout? [y/N]" checkout
+read -r -p "Do you want to force the checkout? [y/N]\n" checkout
+checkout="${checkout:-n}"
 case "${checkout}" in
 y | Y)
     cf checkout -f "${branch}" || exit
